### PR TITLE
Remove reverse ordering of when statements, so they flow from top to bottom

### LINKED ISSUE #37: Choose-whens are not tested in sequential order
Eg.
```
    <Choose>
        <When condition={this.props.when1}>
            <span>WhenBlock1</span>
        </When>
        <When condition={this.props.when2}>
            <span>WhenBlock2</span>
        </When>
        <Otherwise>
            <span>OtherwiseBlock</span>
        </Otherwise>
    </Choose>
```
    it('should render the first block when both conditions true', function () {
      var rendered = util.render(Fixture, {when1: true, when2: true});
      expect(rendered).to.match(util.matchTextWithinSpan('WhenBlock1'));
    });

fails - it renders `WhenBlock2`.

### PR DESCRIPTION
**Pull request by RacingTadpole**
Fixes #37.

### CODE REVIEW

**Comment by texttechne** [comment]
The bugfix is correct and the test case was obviously missing.

Two things before merging this:

1.  I think there is exactly one test missing: If two `<when>` blocks are given and their conditions are both true, then only the content of the first block should be used => this test belongs to the section "requiring in component with choose" 

1. The fixture with three test cases is not needed then. You could use the existing `choose.jsx` as fixture.

**Comment by RacingTadpole** [comment]
Great, thanks. I agree a single test of two `when`s is much neater than my 8 tests of all the combinations of three `when`s and an `otherwise`. I went for the longer series of tests because I wanted to convince myself it really worked, ie. that there wasn't some other heuristic for determining order that just happened to work for two `when`s. But it may be overkill - I'm happy either way.

**Comment by RacingTadpole** [comment]
For good measure I've added the two-`when` test case you describe - it seems right to make that group of specs complete, whether we keep the three-`when` specs or not. :-)

**Comment by AlexGilleran** [comment]
I'm happy with this when you are @texttechne :)

**Comment by texttechne** [comment]
Sorry, I haven't explained enough. I would like to drop the spec with the three `when`s including the accompanying test, because it is overkill, and only want to keep the one two-when test case. 

The reasoning behind this is, that tests require some maintenance effort and can also serve as documentation. So adding too much means more work and waters down the explanatory power of the tests.
> I went for the longer series of tests because I wanted to convince myself it really worked, ie. that there wasn't some other heuristic for determining order that just happened to work for two whens. 

That's an absolutely fine and valid approach, especially if you're working with code from someone else. But I'm pretty sure that only one test case suffices and all other test cases are already covered. 

So all I'm saying is: It is a little bit too much, otherwise it is the perfect commit. So thanks for your contribution!

**Comment by RacingTadpole** [comment]
No worries, I can see what you're saying. The latest version only has the one extra test case.

**Pull request merged**
