### PR TITLE
Added <IfNot> statement

### PR DESCRIPTION
**Pull request by expobrain**
Added the `<IfNot>` statement, works same as the `<If>` statement but resolves when the condition if false

### CODE REVIEW

**Comment by AlexGilleran** [comment]
Hi @expobrain, thanks for contributing :).

I didn't see an issue created for this though - can you explain the advantage this has over `<If condition={! ... }>`? Is it intended to be neater?

**Comment by expobrain** [comment]
Hi @AlexGilleran,

sorry I forgot to open the issue before anything else.

I'm using this package in my current project and sometimes I need to use the `<If>` statement with a negated condition, so I found more readable having a `<IfNot condition={true}>` instead of `<If condition={!true}>`.

**Comment by AlexGilleran** [comment]
OK - I'm not inclined to merge this seeing as imho it doesn't really add enough to warrant having to maintain another 160 lines of code - happy to hear counter-arguments.

**Comment by expobrain** [comment]
I understand that the `<IfNot>` is a more corner case than a feature for this package, I just found it useful enough to open a PR and add the extra LoC. Anyway fair enough if you are not happy to merge it, at the end it's your right :)

**Pull request closed without merging**
