### PR TITLE
Allow for empty control statements

### PR DESCRIPTION
**Pull request by texttechne**
There seems to be no good reason why control statements must have child elements.

### CODE REVIEW

**Comment by AlexGilleran** [comment]
I think I might be missing something, but what's the point of having an empty control statement? Wouldn't this be an error in basically every case?

Or do you want to allow it for cases where you're halfway through development and you write a control statement but haven't written anything to go in it yet?

**Comment by texttechne** [comment]
Yep, I thought of exactly that use case or that you just quickly comment out one block of an if / else.

And in any case, it's perfectly fine to write `if (true) {}` in JS, so why should we forbid this usage. It's more of a linting issue than an error...

**Comment by jimfb** [comment]
Yeah, I agree, it seems intuitively good to support this pattern (if for no other reason than perceived completeness).  It's a perfectly legitimate, though admittedly odd, block of code.

**Comment by AlexGilleran** [comment]
Cool then, makes sense :). Maybe I'll do a PR for the eslint plugin one day.

**Comment by texttechne** [comment]
Was more or less just part of a refactoring, which I pushed just now. But since this might affect the ESLint plugin I thought we should track it here. By the way, @vkbansal seems to be open for making further changes to the ESLint plugin. But I think a linting warning seems to be appropriate in this case, so I don't know if the plugin needs any changes at all...

@AlexGilleran Although I can push to this repo I will still open PR's so you can review them (maybe not every little refactoring or small doc changes). Is this ok with you? Or is it better to PR everything to better keep track?

**Comment by AlexGilleran** [comment]
Nah, I'd say you've proven yourself more than qualified to make those sort of changes unreviewed. I'd still appreciate a PR for big API or algorithmic changes though, and I'll do the same :).

**Comment by vkbansal** [comment]
@texttechne can you open an issue on the ESlint plugin repo?

**Comment by texttechne** [comment]
Agreed. Another thing, more related to this issue. In return for dropping two error messages I wanted to add two new ones for the `<For>` statement: We know in advance, i.e. compile time, that `each` and `index` must be strings, so errors are thrown appropriately. Unfortunately the other attributes cannot be tested, since their value is only known at runtime... 

Might also be worth another rule for @vkbansal

**Comment by texttechne** [comment]
Done. vkbansal/eslint-plugin-jsx-control-statements/issues/2

**Comment by AlexGilleran** [comment]
>Agreed. Another thing, more related to this issue. In return for dropping two error messages I wanted to add two new ones for the <For> statement: We know in advance, i.e. compile time, that each and index must be strings, so errors are thrown appropriately if expressions are specified. Unfortunately the other attributes cannot be tested, since their value is only known at runtime...

Makes sense to me.

**Pull request merged**
